(()=>{
'use strict';
const $=id=>document.getElementById(id);
const SAMPLES=180, W=320, H=240;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const normAng=a=>{while(a<=-Math.PI)a+=Math.PI*2;while(a>Math.PI)a-=Math.PI*2;return a};
const wheel=[0,32,15,19,4,21,2,25,17,34,6,27,13,36,11,30,8,23,10,5,24,16,33,1,20,14,31,9,22,18,29,7,28,12,35,3,26];
let stream=null,running=false,raf=0,prevGray=null,prevProfile=null,lastT=0;
let cx=W/2,cy=H/2,R=92,calibQ=0,ballAngle=null,ballRpmEMA=null,wheelRpmEMA=null;
let wheelFirst=null,ballFirst=null,sampleStart=null,lastBallSamples=[],lastWheelSamples=[];
let sourceMode='none';
const video=$('visionVideo'), canvas=$('visionCanvas'), ctx=canvas?.getContext('2d',{willReadFrequently:true});
if(!video||!canvas||!ctx)return;
canvas.width=W;canvas.height=H;
function status(msg,kind='neutral'){$('visionStatus').textContent=msg;$('visionBadge').textContent=kind==='good'?'مقروء تلقائياً':kind==='warn'?'يحتاج تثبيت':'جاهز';$('visionBadge').className='badge '+kind;}
function setField(id,val){const el=$(id);if(!el||val==null||!Number.isFinite(Number(val)))return;el.value=typeof val==='number'?val.toFixed(2):val;el.dispatchEvent(new Event('input',{bubbles:true}));}
function clickDir(group,val){const b=document.querySelector(`[data-${group}="${val}"]`);if(b&&!b.classList.contains('active'))b.click();}
function grayFrom(img){const d=img.data,g=new Uint8Array(W*H);for(let i=0,j=0;i<d.length;i+=4,j++)g[j]=(d[i]*3+d[i+1]*6+d[i+2])>>3;return g;}
function autoCalibrate(gray){if(!prevGray)return;let sw=0,sx=0,sy=0;const pts=[];for(let y=12;y<H-12;y+=2){for(let x=12;x<W-12;x+=2){const i=y*W+x,df=Math.abs(gray[i]-prevGray[i]);if(df<16)continue;const edge=Math.abs(gray[i]-gray[i-1])+Math.abs(gray[i]-gray[i-W]);const w=df+0.35*edge;sw+=w;sx+=x*w;sy+=y*w;pts.push([x,y,w]);}}
 if(sw<18000)return;const ncx=sx/sw,ncy=sy/sw;if(ncx<45||ncx>W-45||ncy<35||ncy>H-35)return;const hist=new Float32Array(140);for(const [x,y,w] of pts){const r=Math.round(Math.hypot(x-ncx,y-ncy));if(r<hist.length)hist[r]+=w;}let peak=0,pr=0;for(let r=45;r<Math.min(118,hist.length);r++){let v=0;for(let k=-3;k<=3;k++)v+=hist[r+k]||0;if(v>peak){peak=v;pr=r;}}if(pr<52)return;cx=0.82*cx+0.18*ncx;cy=0.82*cy+0.18*ncy;R=0.82*R+0.18*pr;calibQ=clamp(calibQ+0.04,0,1);}
function sampleRing(gray,rad){const a=new Float32Array(SAMPLES);for(let k=0;k<SAMPLES;k++){const ang=2*Math.PI*k/SAMPLES;let s=0,c=0;for(const dr of [-2,0,2]){const x=Math.round(cx+(rad+dr)*Math.cos(ang)),y=Math.round(cy+(rad+dr)*Math.sin(ang));if(x>=1&&x<W-1&&y>=1&&y<H-1){s+=gray[y*W+x];c++;}}a[k]=c?s/c:0;}let mean=0;for(const v of a)mean+=v;mean/=SAMPLES;for(let i=0;i<SAMPLES;i++)a[i]-=mean;return a;}
function bestShift(a,b,max=15){if(!a||!b)return null;let best=-Infinity,bs=0;for(let sh=-max;sh<=max;sh++){let s=0,aa=0,bb=0;for(let i=0;i<SAMPLES;i++){const j=(i+sh+SAMPLES)%SAMPLES;s+=a[i]*b[j];aa+=a[i]*a[i];bb+=b[j]*b[j];}const q=s/Math.sqrt(aa*bb+1e-9);if(q>best){best=q;bs=sh;}}return {shift:bs,quality:best};}
function detectBall(img,gray){if(!prevGray)return null;const d=img.data;let best=-1,bang=0;const bins=new Float32Array(SAMPLES);for(let k=0;k<SAMPLES;k++){const ang=2*Math.PI*k/SAMPLES;let score=0;for(let rr=.78;rr<=1.04;rr+=.045){const x=Math.round(cx+R*rr*Math.cos(ang)),y=Math.round(cy+R*rr*Math.sin(ang));if(x<1||x>=W-1||y<1||y>=H-1)continue;const i=y*W+x,p=i*4;const motion=Math.abs(gray[i]-prevGray[i]);const bright=(d[p]+d[p+1]+d[p+2])/3;const white=bright-Math.abs(d[p]-d[p+1])*.3-Math.abs(d[p+1]-d[p+2])*.3;score+=motion*1.6+Math.max(0,white-105)*.42;}bins[k]=score;}
 for(let k=0;k<SAMPLES;k++){const v=(bins[(k-1+SAMPLES)%SAMPLES]+2*bins[k]+bins[(k+1)%SAMPLES])/4;if(v>best){best=v;bang=2*Math.PI*k/SAMPLES;}}
 return best>55?{angle:bang,quality:clamp((best-55)/150,0,1)}:null;}
function detectZero(img){const d=img.data;let best=-1,bang=null;for(let k=0;k<SAMPLES;k++){const ang=2*Math.PI*k/SAMPLES;let s=0,c=0;for(let rr=.48;rr<=.72;rr+=.04){const x=Math.round(cx+R*rr*Math.cos(ang)),y=Math.round(cy+R*rr*Math.sin(ang));if(x<0||x>=W||y<0||y>=H)continue;const p=(y*W+x)*4,r=d[p],g=d[p+1],b=d[p+2];s+=g-Math.max(r,b)*.72-Math.abs(r-b)*.15;c++;}const q=c?s/c:-999;if(q>best){best=q;bang=ang;}}return best>28?{angle:bang,quality:clamp((best-28)/70,0,1)}:null;}
function pocketAtMarker(zeroAngle){const marker=-Math.PI/2;let cw=(marker-zeroAngle)%(Math.PI*2);if(cw<0)cw+=Math.PI*2;const idx=Math.round(cw/(Math.PI*2)*37)%37;return wheel[idx];}
function ema(old,v,a=.3){return old==null?v:old*(1-a)+v*a;}
function updateAnomaly(ballRpm,q){if(ballRpm==null)return;lastBallSamples.push(ballRpm);if(lastBallSamples.length>12)lastBallSamples.shift();if(lastBallSamples.length<5)return;const m=lastBallSamples.reduce((a,b)=>a+b,0)/lastBallSamples.length;const dev=Math.sqrt(lastBallSamples.reduce((a,b)=>a+(b-m)*(b-m),0)/lastBallSamples.length)/(m+1e-6);let sev=0,kind='normal';if(q<.18||dev>.32){sev=3;kind='erratic'}else if(dev>.22){sev=2;kind='erratic'}else if(dev>.14){sev=1;kind='long_bounce'}$('anomaly').value=kind;$('anomaly').dispatchEvent(new Event('change',{bubbles:true}));setField('bounceSeverity',sev);}
function overlay(ball,zero,wdir,bdir,wr,br){ctx.save();ctx.lineWidth=2;ctx.strokeStyle='rgba(37,99,235,.9)';ctx.beginPath();ctx.arc(cx,cy,R,0,Math.PI*2);ctx.stroke();ctx.strokeStyle='rgba(16,185,129,.9)';ctx.beginPath();ctx.arc(cx,cy,R*.62,0,Math.PI*2);ctx.stroke();if(ball){ctx.fillStyle='rgba(245,158,11,.95)';ctx.beginPath();ctx.arc(cx+R*.92*Math.cos(ball.angle),cy+R*.92*Math.sin(ball.angle),5,0,Math.PI*2);ctx.fill();}if(zero){ctx.strokeStyle='rgba(34,197,94,.95)';ctx.beginPath();ctx.moveTo(cx,cy);ctx.lineTo(cx+R*.68*Math.cos(zero.angle),cy+R*.68*Math.sin(zero.angle));ctx.stroke();}ctx.fillStyle='rgba(0,0,0,.72)';ctx.fillRect(4,4,190,42);ctx.fillStyle='#fff';ctx.font='12px -apple-system,Arial';ctx.fillText(`Wheel ${wr?.toFixed(1)??'—'} RPM ${wdir||''}`,10,20);ctx.fillText(`Ball ${br?.toFixed(1)??'—'} RPM ${bdir||''}`,10,38);ctx.restore();}
function frame(t){if(!running||video.readyState<2){raf=requestAnimationFrame(frame);return;}ctx.drawImage(video,0,0,W,H);const img=ctx.getImageData(0,0,W,H),gray=grayFrom(img);autoCalibrate(gray);const dt=lastT?(t-lastT)/1000:0;let wr=null,br=null,wdir='unknown',bdir='unknown';const prof=sampleRing(gray,R*.62),sh=bestShift(prevProfile,prof,18);if(sh&&dt>.04&&dt<.7&&sh.quality>.18){const deg=sh.shift*(360/SAMPLES);const rpm=Math.abs(deg/dt)/360*60;if(rpm>.3&&rpm<40){wheelRpmEMA=ema(wheelRpmEMA,rpm,.25);wr=wheelRpmEMA;wdir=deg>0?'ccw':'cw';clickDir('wheel-dir',wdir);lastWheelSamples.push(wr);if(lastWheelSamples.length>8)lastWheelSamples.shift();}}
 const ball=detectBall(img,gray);if(ball&&ballAngle!=null&&dt>.04&&dt<.7){const da=normAng(ball.angle-ballAngle);const rpm=Math.abs(da/dt)/Math.PI/2*60;if(rpm>1&&rpm<180){ballRpmEMA=ema(ballRpmEMA,rpm,.35);br=ballRpmEMA;bdir=da>0?'cw':'ccw';clickDir('ball-dir',bdir);updateAnomaly(br,ball.quality);}}if(ball)ballAngle=ball.angle;
 const zero=detectZero(img);if(zero){setField('refPocket',pocketAtMarker(zero.angle));}
 const now=performance.now()/1000;if(wr&&br){if(sampleStart==null){sampleStart=now;wheelFirst=wr;ballFirst=br;setField('wheelRpm1',wr);setField('ballRpm1',br);}setField('wheelRpm2',wr);setField('ballRpm2',br);setField('sampleGap',Math.max(.1,now-sampleStart));}
 const autoQ=(sh?clamp((sh.quality-.1)/.55,0,1):0)*.35+(ball?ball.quality:0)*.35+(zero?zero.quality:0)*.2+calibQ*.1;$('visionQuality').textContent=Math.round(autoQ*100)+'%';if(autoQ>.62)status('القراءة التلقائية شغالة: السرعات + الاتجاه + مرجع الجيب تتحدث مباشرة.','good');else if(autoQ>.35)status('القراءة شغالة لكن ثبّت الكاميرا وخلي العجلة كاملة وواضحة.','warn');else status('أحاول أقفل على العجلة والكورة… قرّب/بعّد لين العجلة تكون كاملة.','neutral');
 overlay(ball,zero,wdir,bdir,wr,br);prevGray=gray;prevProfile=prof;lastT=t;raf=requestAnimationFrame(frame);}
async function startCamera(){stopSource();try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1280},height:{ideal:720},frameRate:{ideal:60,max:60}},audio:false});video.srcObject=stream;video.removeAttribute('src');await video.play();sourceMode='camera';$('visionStartBtn').textContent='إيقاف التحليل';resetTracker();running=true;raf=requestAnimationFrame(frame);status('الكاميرا شغالة. وجّهها للعجلة وخليها كاملة داخل الصورة.','neutral');}catch(e){status('ما قدرت أفتح الكاميرا. اسمح للكاميرا من إعدادات Safari أو استخدم فيديو محفوظ.','bad');}}
function stopSource(){running=false;if(raf)cancelAnimationFrame(raf);raf=0;if(stream){stream.getTracks().forEach(t=>t.stop());stream=null;}video.pause();}
function resetTracker(){prevGray=null;prevProfile=null;lastT=0;ballAngle=null;ballRpmEMA=null;wheelRpmEMA=null;wheelFirst=null;ballFirst=null;sampleStart=null;lastBallSamples=[];lastWheelSamples=[];calibQ=0;cx=W/2;cy=H/2;R=92;}
$('visionCameraBtn').addEventListener('click',startCamera);
$('visionStartBtn').addEventListener('click',()=>{if(running){running=false;$('visionStartBtn').textContent='بدء التحليل';status('التحليل متوقف — الصورة موجودة لكن القيم مجمّدة.','neutral');}else{if(video.readyState>=2){running=true;resetTracker();$('visionStartBtn').textContent='إيقاف التحليل';raf=requestAnimationFrame(frame);}else startCamera();}});
$('visionResetBtn').addEventListener('click',()=>{resetTracker();status('تمت إعادة القفل التلقائي.','neutral');});
$('visionFile').addEventListener('change',async e=>{const f=e.target.files?.[0];if(!f)return;stopSource();video.srcObject=null;video.src=URL.createObjectURL(f);video.loop=false;video.muted=true;await video.play();sourceMode='file';resetTracker();running=true;$('visionStartBtn').textContent='إيقاف التحليل';raf=requestAnimationFrame(frame);status('أحلل الفيديو المحفوظ تلقائياً…','neutral');});
window.addEventListener('beforeunload',stopSource);
status('جاهز — افتح الكاميرا أو اختر فيديو.','neutral');
})();
